from __future__ import annotations

from dataclasses import replace

from .game_type import GenreProfile

GENRE_PROFILES = [
    GenreProfile(
        genre_id="idle_rpg",
        description="Games that auto-play over time, where players log in to claim resources and upgrade.",
        common_ui_states=["reward", "upgrade", "battle"],
        common_labels=["afk", "claim", "idle", "offline", "chest", "auto"],
        control_style="menu_heavy",
        safe_default_actions=["claim_reward", "start_auto_battle", "free_summon"],
        risky_actions=["spend_premium_currency", "dismiss_hero"],
        progression_loop="Wait -> Claim -> Upgrade -> Push Stage",
        reward_patterns="Offline rewards chest, daily logins.",
        upgrade_patterns="Linear level ups, gear equipping.",
    ),
    GenreProfile(
        genre_id="action_rpg",
        description="Real-time combat games focusing on character movement, dodging, and skill activation.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["attack", "dodge", "skill", "combo", "inventory", "equip"],
        control_style="joystick_and_buttons",
        safe_default_actions=["auto_combat", "dodge"],
        risky_actions=["sell_gear", "enter_high_level_dungeon"],
        progression_loop="Grind Dungeons -> Loot -> Upgrade -> Boss",
        reward_patterns="Loot drops, dungeon clears.",
        upgrade_patterns="Refining gear, skill trees.",
    ),
    GenreProfile(
        genre_id="strategy_rts",
        description="Real-time strategy games involving base building and unit deployment.",
        common_ui_states=["menu", "battle", "upgrade"],
        common_labels=["build", "upgrade", "train", "deploy", "base", "attack", "alliance"],
        control_style="tap_and_drag",
        safe_default_actions=["collect_resources", "train_basic_units", "upgrade_resource_building"],
        risky_actions=["attack_other_player", "use_speedups"],
        progression_loop="Build -> Train -> Gather -> Attack",
        reward_patterns="Resource gathering, daily quests.",
        upgrade_patterns="Building timers, research trees.",
    ),
    GenreProfile(
        genre_id="city_builder",
        description="Games focused on placing buildings, managing resources, and expanding a settlement.",
        common_ui_states=["menu", "upgrade"],
        common_labels=["build", "collect", "expand", "decorate", "harvest", "citizens"],
        control_style="drag_and_drop",
        safe_default_actions=["collect_taxes", "harvest_crops", "build_road"],
        risky_actions=["spend_gems_to_finish"],
        progression_loop="Harvest -> Build -> Wait -> Expand",
        reward_patterns="Time-based resource generation.",
        upgrade_patterns="Upgrading HQ, unlocking new building types.",
    ),
    GenreProfile(
        genre_id="card_battler",
        description="Games centered around building a deck of cards and playing them in turn-based combat.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["draw", "play", "end turn", "deck", "mana", "energy", "discard"],
        control_style="drag_to_target",
        safe_default_actions=["play_affordable_card", "end_turn"],
        risky_actions=["dust_card", "concede"],
        progression_loop="Battle -> Get Packs -> Edit Deck -> Battle",
        reward_patterns="Card packs, ranked rewards.",
        upgrade_patterns="Crafting cards, level up cards.",
    ),
    GenreProfile(
        genre_id="auto_battler",
        description="Games where players draft units and place them on a board, then watch combat resolve automatically.",
        common_ui_states=["battle", "menu"],
        common_labels=["refresh", "buy", "sell", "level up", "synergy", "deploy", "round"],
        control_style="drag_and_drop_timed",
        safe_default_actions=["buy_unit_from_shop", "place_unit", "refresh_shop"],
        risky_actions=["sell_upgraded_unit", "spend_all_gold"],
        progression_loop="Draft -> Deploy -> Observe Combat -> Economy",
        reward_patterns="Gold per round, streak bonuses.",
        upgrade_patterns="Combining duplicates into higher star tiers.",
    ),
    GenreProfile(
        genre_id="tower_defense",
        description="Games where players place defensive structures to stop waves of enemies.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["build", "upgrade", "sell", "wave", "start", "base", "tower"],
        control_style="tap_to_place",
        safe_default_actions=["build_basic_tower", "start_wave", "upgrade_tower"],
        risky_actions=["sell_tower_during_wave"],
        progression_loop="Build Defense -> Survive Wave -> Upgrade Defense",
        reward_patterns="Gold per kill, stage clear stars.",
        upgrade_patterns="In-match tower upgrades, persistent skill trees.",
    ),
    GenreProfile(
        genre_id="gacha_collector",
        description="Character collection games heavily focused on rolling for new units via a random 'gacha' system.",
        common_ui_states=["menu", "reward", "battle", "upgrade"],
        common_labels=["summon", "pull", "roster", "banner", "pity", "claim", "event"],
        control_style="menu_heavy",
        safe_default_actions=["claim_daily_missions", "do_free_pull", "sweep_stage"],
        risky_actions=["spend_premium_currency_on_standard_banner"],
        progression_loop="Farm Materials -> Pull Gacha -> Level Character -> Spark",
        reward_patterns="Dailies, event milestones, login bonuses.",
        upgrade_patterns="Level up, ascend, skill enhance, equip artifacts.",
    ),
    GenreProfile(
        genre_id="mmorpg",
        description="Massively multiplayer online role-playing games with open worlds, quests, and social features.",
        common_ui_states=["battle", "menu", "upgrade", "tutorial"],
        common_labels=["quest", "party", "guild", "inventory", "chat", "map", "mount", "auto-path"],
        control_style="hybrid_joystick_and_menus",
        safe_default_actions=["auto_quest", "accept_quest", "claim_achievements"],
        risky_actions=["pk", "leave_guild", "destroy_equipment"],
        progression_loop="Questing -> Dungeons -> Raids -> Daily Tasks",
        reward_patterns="Quest turn-ins, boss loot, daily activities.",
        upgrade_patterns="Gear enhancement, level up, mount leveling.",
    ),
    GenreProfile(
        genre_id="match3_puzzle",
        description="Puzzle games where the player matches 3 or more of the same item to clear them from a board.",
        common_ui_states=["battle", "menu", "reward"],
        common_labels=["play", "moves", "score", "lives", "boosters", "goals"],
        control_style="swipe_to_swap",
        safe_default_actions=["match_three", "use_free_booster"],
        risky_actions=["buy_extra_moves_with_gold"],
        progression_loop="Play Level -> Earn Stars -> Progress Map",
        reward_patterns="Level completion chests, daily spins.",
        upgrade_patterns="Unlocking pre-match boosters.",
    ),
    GenreProfile(
        genre_id="social_casino",
        description="Casino-style games (slots, poker) simulating gambling with virtual currency.",
        common_ui_states=["menu", "battle", "reward"],
        common_labels=["spin", "bet", "max bet", "jackpot", "chips", "free coins", "collect"],
        control_style="button_mashing",
        safe_default_actions=["claim_hourly_bonus", "spin_minimum_bet"],
        risky_actions=["max_bet"],
        progression_loop="Collect Free Chips -> Spin -> Level Up -> Spin Higher",
        reward_patterns="Hourly lobby bonus, level up bonuses.",
        upgrade_patterns="Unlocking new slot machines at higher levels.",
    ),
    GenreProfile(
        genre_id="fps_shooter",
        description="First-person or third-person shooters focusing on aiming and reflex combat.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["fire", "reload", "jump", "crouch", "loadout", "matchmaking", "aim"],
        control_style="dual_virtual_joysticks",
        safe_default_actions=["fire", "reload", "find_match"],
        risky_actions=["change_sensitivity_settings"],
        progression_loop="Play Match -> Earn XP -> Unlock Attachments",
        reward_patterns="Battle pass progression, match completion.",
        upgrade_patterns="Weapon attachments, perks, skins.",
    ),
    GenreProfile(
        genre_id="moba",
        description="Multiplayer online battle arenas where teams compete to destroy the opponent's base.",
        common_ui_states=["battle", "menu"],
        common_labels=["attack", "skill", "recall", "shop", "push", "defend", "lane"],
        control_style="joystick_and_skill_aiming",
        safe_default_actions=["buy_recommended_item", "recall_to_base"],
        risky_actions=["tower_dive", "sell_core_item"],
        progression_loop="Farm Minions -> Buy Items -> Teamfight -> Push Base",
        reward_patterns="Match completion gold, ranked points.",
        upgrade_patterns="In-match item purchasing.",
    ),
    GenreProfile(
        genre_id="racing",
        description="Vehicle racing against opponents or time limits.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["race", "nitro", "brake", "steer", "garage", "tune", "drift"],
        control_style="tilt_or_on_screen_buttons",
        safe_default_actions=["accelerate", "use_nitro"],
        risky_actions=["sell_car"],
        progression_loop="Race -> Earn Credits -> Tune Car -> Harder Race",
        reward_patterns="Race finishing position, seasonal rewards.",
        upgrade_patterns="Engine turning, tires, nitrous upgrades.",
    ),
    GenreProfile(
        genre_id="sports_manager",
        description="Management simulation of a sports team, focusing on roster, tactics, and economy.",
        common_ui_states=["menu", "upgrade"],
        common_labels=["squad", "tactics", "transfer", "train", "stadium", "match", "scout"],
        control_style="menu_heavy",
        safe_default_actions=["play_next_match", "train_squad"],
        risky_actions=["sell_star_player", "go_bankrupt"],
        progression_loop="Manage Squad -> Play Match -> Earn Revenue -> Upgrade Team",
        reward_patterns="League finishing position, ticket sales.",
        upgrade_patterns="Player stat growth, stadium expansion.",
    ),
    GenreProfile(
        genre_id="survival_crafting",
        description="Games centered around gathering resources in a hostile environment to survive and build shelters.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["gather", "craft", "eat", "drink", "inventory", "build", "health"],
        control_style="joystick_and_interaction_buttons",
        safe_default_actions=["gather_wood", "eat_food", "craft_tool"],
        risky_actions=["fight_boss_unprepared", "eat_poison"],
        progression_loop="Gather -> Craft -> Build -> Explore",
        reward_patterns="Resource nodes, exploring rare areas.",
        upgrade_patterns="Crafting tier progression, base expansion.",
    ),
    GenreProfile(
        genre_id="sandbox_sim",
        description="Open-ended games where creativity and simulation rule over strict objectives.",
        common_ui_states=["battle", "menu"],
        common_labels=["create", "spawn", "tool", "world", "save", "load", "physics"],
        control_style="variable",
        safe_default_actions=["spawn_item", "save_world"],
        risky_actions=["delete_world"],
        progression_loop="Create -> Experiment -> Modify",
        reward_patterns="Unlocking new tools/materials.",
        upgrade_patterns="Tool unlocks or completely open from the start.",
    ),
    GenreProfile(
        genre_id="turn_based_rpg",
        description="Role-playing games where combat is decided by taking turns and selecting commands.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["attack", "defend", "magic", "item", "flee", "party", "turn"],
        control_style="menu_heavy",
        safe_default_actions=["use_basic_attack", "heal_low_hp"],
        risky_actions=["flee_from_boss", "use_rare_elixir"],
        progression_loop="Explore -> Turn-Based Combat -> Earn XP -> Level Up",
        reward_patterns="Victory loot, boss chests.",
        upgrade_patterns="Leveling up, unlocking new skills.",
    ),
    GenreProfile(
        genre_id="roguelike",
        description="Games featuring procedurally generated levels and permadeath or meta-progression loops.",
        common_ui_states=["battle", "menu", "upgrade"],
        common_labels=["start run", "death", "choose boon", "floor", "boss", "meta-upgrade"],
        control_style="joystick_or_tap",
        safe_default_actions=["choose_health_upgrade", "enter_next_room"],
        risky_actions=["take_cursed_item", "abandon_run"],
        progression_loop="Start Run -> Fight -> Die -> Buy Meta Upgrades -> Repeat",
        reward_patterns="Temporary run buffs, permanent meta currency.",
        upgrade_patterns="In-run temporary stats, out-of-run permanent buffs.",
    ),
    GenreProfile(
        genre_id="tycoon_management",
        description="Economic simulation games focused on growing a business and maximizing profit.",
        common_ui_states=["menu", "upgrade"],
        common_labels=["upgrade", "hire", "expand", "profit", "invest", "collect", "manager"],
        control_style="menu_heavy",
        safe_default_actions=["collect_money", "upgrade_cheapest_generator", "hire_manager"],
        risky_actions=["prestige_too_early"],
        progression_loop="Earn Money -> Upgrade Generator -> Earn Faster -> Prestige",
        reward_patterns="Offline earnings, ad-multiplier, investors.",
        upgrade_patterns="Generator levels, prestige multipliers.",
    ),
]

def _parse_loop(value: str) -> list[str]:
    if not value.strip():
        return []
    parts = [part.strip() for part in value.split("->")]
    return [part for part in parts if part]


def _enrich_profile(profile: GenreProfile) -> GenreProfile:
    safe_repeat_actions = profile.safe_repeat_actions or list(profile.safe_default_actions)
    stop_conditions = profile.stop_conditions or list(profile.risky_actions) + [
        "security_boundary_detected",
        "unknown_state_streak",
        "low_action_confidence",
    ]
    reward_loop = profile.reward_loop or [profile.reward_patterns.strip()] if profile.reward_patterns.strip() else []
    upgrade_loop = profile.upgrade_loop or [profile.upgrade_patterns.strip()] if profile.upgrade_patterns.strip() else []
    return replace(
        profile,
        progression_path=profile.progression_path or _parse_loop(profile.progression_loop),
        reward_loop=reward_loop,
        upgrade_loop=upgrade_loop,
        safe_repeat_actions=safe_repeat_actions,
        stop_conditions=stop_conditions,
    )


GENRE_PROFILES = [_enrich_profile(profile) for profile in GENRE_PROFILES]

GENRE_PROFILE_REGISTRY = {p.genre_id: p for p in GENRE_PROFILES}
